In [1]:
import numpy as np

a = np.array([2,4,6])
print(a)

[2 4 6]


In [2]:
import numpy as np

a = np.array([2,4,6])
print(a)
value = a[2]
print(value)

[2 4 6]
6


In [3]:
import numpy as np

a = np.array([[2,3,4],[6,7,8]])
print(a)

[[2 3 4]
 [6 7 8]]


In [4]:
import numpy as np

a = np.array([[2,3,4],[6,7,8]])
print(a)
value = a[1,2]
print(value)

[[2 3 4]
 [6 7 8]]
8


In [5]:
import numpy as np

a = np.array([2,4,6])
a[2] = 10
print(a)

[ 2  4 10]


In [6]:
import numpy as np

a = np.array([[2,3,4],[6,7,8]])
print(a)

a[1,2]=20
print(a)

[[2 3 4]
 [6 7 8]]
[[ 2  3  4]
 [ 6  7 20]]
